
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]

modId="${mod_id}"
version="${mod_version}"
authors="${mod_authors}"
logoFile = "delab_logo.png"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config = "delab.mixins.json"

